#!/bin/bash
# Generated by cyber-sandbox.
#
# Runs as root with CAP_NET_ADMIN so it can install the egress policy, starts the
# gateway, and then hands the rest of the container's life to a process tree whose
# bounding set no longer contains CAP_NET_ADMIN. Nothing after that point can alter the
# packet filter, including a process that has become root inside the sandbox.
set -euo pipefail

readonly GATEWAY_USER={{ gateway_user }}
readonly AUDIT_TRAIL={{ audit_trail }}
readonly CA_CERTIFICATE={{ ca_certificate }}
readonly AUTHORIZED_KEYS={{ authorized_keys }}
readonly GATEWAY=/usr/local/bin/cyber-sandbox-gateway

/usr/local/lib/cyber-sandbox/egress-policy.sh

install -d -o "${GATEWAY_USER}" -g "${GATEWAY_USER}" -m 0750 "$(dirname "${AUDIT_TRAIL}")"

# The authority is minted in its own run, so it is on disk and in the sandbox's trust
# store before anything is listening. Waiting on a file a background process may or may
# not have written yet would make the first outbound connection a race.
setpriv --reuid="${GATEWAY_USER}" --regid="${GATEWAY_USER}" --clear-groups \
  "${GATEWAY}" init-ca --ca-certificate "${CA_CERTIFICATE}"

cp "${CA_CERTIFICATE}" /usr/local/share/ca-certificates/cyber-sandbox-gateway.crt
update-ca-certificates >/dev/null

# The gateway keeps CAP_NET_ADMIN through the uid change by way of the file capability
# set on its binary, which the image build verifies. It needs it to bind the netfilter
# log group the packet filter reports refused packets on; it is not enough to change any
# rule, and the researcher account cannot execute the binary at all.
setpriv --reuid="${GATEWAY_USER}" --regid="${GATEWAY_USER}" --clear-groups \
  "${GATEWAY}" serve \
    --sandbox "${CYBER_SANDBOX_NAME}" \
    --audit-trail "${AUDIT_TRAIL}" \
    --ca-certificate "${CA_CERTIFICATE}" \
    --proxy-port {{ proxy_port }} \
    --dns-port {{ dns_port }} \
    --nflog-group {{ nflog_group }} \
    --upstream-resolver "${CYBER_SANDBOX_RESOLVER}" &

# The host's public key arrives in the environment rather than on a mount. sshd refuses an
# authorized-keys file it does not consider safely owned, and a file this script writes as
# root satisfies that without depending on how the runtime maps uids across virtiofs.
install -d -o root -g root -m 0755 "$(dirname "${AUTHORIZED_KEYS}")"
printf '%s\n' "${CYBER_SANDBOX_AUTHORIZED_KEY}" >"${AUTHORIZED_KEYS}"
chown root:root "${AUTHORIZED_KEYS}"
chmod 0644 "${AUTHORIZED_KEYS}"

ssh-keygen -A
exec capsh --drop=cap_net_admin,cap_sys_module,cap_sys_rawio -- \
  -c 'exec /usr/sbin/sshd -D -e'
